#######################################
#          UHC - TAUPE - RUN          #
#######################################

##########          WARNING          ##########
#   Warning ! The options that are commented out (with a hash in front)
#   are not yet implemented (probably because you are using a beta version of the plugin,
#   do not hesitate to check if a more recent version is available : [https://github.com/IAmNonog/MC-UHCRun] )
###############################################
spawn:
  buildSpawn: true
  #coordonate of the center of the spawn
  coordonate:
    x: 0
    y: 200
    z: 0
game:
  map: "world"
  #Size of border (1000x1000 by default)
  map-size: 1000
  gradualReduction:
    enableReduction: true
    #Time in minutes
    TimeBeforeReduction: 20
    mapSizeAfterReduction: 400
    #Number of reduction blocks per second
    ReductionSpeed: 1
run:
  enableRun: false
#  generation:
#    #Warning ! this is an experimental system who made a lot of lag (/uhc generate)
#    increaseOreGeneration: false
taupe:
  enableTaupe: false
  #Time (in minutes) before announce of taupe
  TimeBeforeReveal: 10
